/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NfcRouteImport } from './routes/nfc'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as CampanhasRouteImport } from './routes/campanhas'
import { Route as BeneficiariosRouteImport } from './routes/beneficiarios'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CSlugIndexRouteImport } from './routes/c.$slug.index'
import { Route as CSlugSobreRouteImport } from './routes/c.$slug.sobre'
import { Route as CSlugProdutosRouteImport } from './routes/c.$slug.produtos'
import { Route as CSlugIndiqueRouteImport } from './routes/c.$slug.indique'
import { Route as CSlugEnquetesRouteImport } from './routes/c.$slug.enquetes'
import { Route as CSlugCuponsRouteImport } from './routes/c.$slug.cupons'
import { Route as CSlugCreditosRouteImport } from './routes/c.$slug.creditos'
import { Route as CSlugClubeRouteImport } from './routes/c.$slug.clube'
import { Route as CSlugBeneficiosRouteImport } from './routes/c.$slug.beneficios'
import { Route as CSlugProdutosProductIdRouteImport } from './routes/c.$slug.produtos.$productId'

const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NfcRoute = NfcRouteImport.update({
  id: '/nfc',
  path: '/nfc',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasRoute = CampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariosRoute = BeneficiariosRouteImport.update({
  id: '/beneficiarios',
  path: '/beneficiarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CSlugIndexRoute = CSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugSobreRoute = CSlugSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugProdutosRoute = CSlugProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugIndiqueRoute = CSlugIndiqueRouteImport.update({
  id: '/indique',
  path: '/indique',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugEnquetesRoute = CSlugEnquetesRouteImport.update({
  id: '/enquetes',
  path: '/enquetes',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugCuponsRoute = CSlugCuponsRouteImport.update({
  id: '/cupons',
  path: '/cupons',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugCreditosRoute = CSlugCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugClubeRoute = CSlugClubeRouteImport.update({
  id: '/clube',
  path: '/clube',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugBeneficiosRoute = CSlugBeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => CSlugRoute,
} as any)
const CSlugProdutosProductIdRoute = CSlugProdutosProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CSlugProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beneficiarios': typeof BeneficiariosRoute
  '/campanhas': typeof CampanhasRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/landing': typeof LandingRoute
  '/nfc': typeof NfcRoute
  '/perfil': typeof PerfilRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/c/$slug/beneficios': typeof CSlugBeneficiosRoute
  '/c/$slug/clube': typeof CSlugClubeRoute
  '/c/$slug/creditos': typeof CSlugCreditosRoute
  '/c/$slug/cupons': typeof CSlugCuponsRoute
  '/c/$slug/enquetes': typeof CSlugEnquetesRoute
  '/c/$slug/indique': typeof CSlugIndiqueRoute
  '/c/$slug/produtos': typeof CSlugProdutosRouteWithChildren
  '/c/$slug/sobre': typeof CSlugSobreRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/c/$slug/produtos/$productId': typeof CSlugProdutosProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/beneficiarios': typeof BeneficiariosRoute
  '/campanhas': typeof CampanhasRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/landing': typeof LandingRoute
  '/nfc': typeof NfcRoute
  '/perfil': typeof PerfilRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/c/$slug/beneficios': typeof CSlugBeneficiosRoute
  '/c/$slug/clube': typeof CSlugClubeRoute
  '/c/$slug/creditos': typeof CSlugCreditosRoute
  '/c/$slug/cupons': typeof CSlugCuponsRoute
  '/c/$slug/enquetes': typeof CSlugEnquetesRoute
  '/c/$slug/indique': typeof CSlugIndiqueRoute
  '/c/$slug/produtos': typeof CSlugProdutosRouteWithChildren
  '/c/$slug/sobre': typeof CSlugSobreRoute
  '/c/$slug': typeof CSlugIndexRoute
  '/c/$slug/produtos/$productId': typeof CSlugProdutosProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/beneficiarios': typeof BeneficiariosRoute
  '/campanhas': typeof CampanhasRoute
  '/catalogo': typeof CatalogoRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/landing': typeof LandingRoute
  '/nfc': typeof NfcRoute
  '/perfil': typeof PerfilRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/c/$slug': typeof CSlugRouteWithChildren
  '/c/$slug/beneficios': typeof CSlugBeneficiosRoute
  '/c/$slug/clube': typeof CSlugClubeRoute
  '/c/$slug/creditos': typeof CSlugCreditosRoute
  '/c/$slug/cupons': typeof CSlugCuponsRoute
  '/c/$slug/enquetes': typeof CSlugEnquetesRoute
  '/c/$slug/indique': typeof CSlugIndiqueRoute
  '/c/$slug/produtos': typeof CSlugProdutosRouteWithChildren
  '/c/$slug/sobre': typeof CSlugSobreRoute
  '/c/$slug/': typeof CSlugIndexRoute
  '/c/$slug/produtos/$productId': typeof CSlugProdutosProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/beneficiarios'
    | '/campanhas'
    | '/catalogo'
    | '/configuracoes'
    | '/financeiro'
    | '/landing'
    | '/nfc'
    | '/perfil'
    | '/admin'
    | '/c/$slug'
    | '/c/$slug/beneficios'
    | '/c/$slug/clube'
    | '/c/$slug/creditos'
    | '/c/$slug/cupons'
    | '/c/$slug/enquetes'
    | '/c/$slug/indique'
    | '/c/$slug/produtos'
    | '/c/$slug/sobre'
    | '/c/$slug/'
    | '/c/$slug/produtos/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/beneficiarios'
    | '/campanhas'
    | '/catalogo'
    | '/configuracoes'
    | '/financeiro'
    | '/landing'
    | '/nfc'
    | '/perfil'
    | '/admin'
    | '/c/$slug/beneficios'
    | '/c/$slug/clube'
    | '/c/$slug/creditos'
    | '/c/$slug/cupons'
    | '/c/$slug/enquetes'
    | '/c/$slug/indique'
    | '/c/$slug/produtos'
    | '/c/$slug/sobre'
    | '/c/$slug'
    | '/c/$slug/produtos/$productId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/beneficiarios'
    | '/campanhas'
    | '/catalogo'
    | '/configuracoes'
    | '/financeiro'
    | '/landing'
    | '/nfc'
    | '/perfil'
    | '/_authenticated/admin'
    | '/c/$slug'
    | '/c/$slug/beneficios'
    | '/c/$slug/clube'
    | '/c/$slug/creditos'
    | '/c/$slug/cupons'
    | '/c/$slug/enquetes'
    | '/c/$slug/indique'
    | '/c/$slug/produtos'
    | '/c/$slug/sobre'
    | '/c/$slug/'
    | '/c/$slug/produtos/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BeneficiariosRoute: typeof BeneficiariosRoute
  CampanhasRoute: typeof CampanhasRoute
  CatalogoRoute: typeof CatalogoRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LandingRoute: typeof LandingRoute
  NfcRoute: typeof NfcRoute
  PerfilRoute: typeof PerfilRoute
  CSlugRoute: typeof CSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfc': {
      id: '/nfc'
      path: '/nfc'
      fullPath: '/nfc'
      preLoaderRoute: typeof NfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas': {
      id: '/campanhas'
      path: '/campanhas'
      fullPath: '/campanhas'
      preLoaderRoute: typeof CampanhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiarios': {
      id: '/beneficiarios'
      path: '/beneficiarios'
      fullPath: '/beneficiarios'
      preLoaderRoute: typeof BeneficiariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/c/$slug/': {
      id: '/c/$slug/'
      path: '/'
      fullPath: '/c/$slug/'
      preLoaderRoute: typeof CSlugIndexRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/sobre': {
      id: '/c/$slug/sobre'
      path: '/sobre'
      fullPath: '/c/$slug/sobre'
      preLoaderRoute: typeof CSlugSobreRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/produtos': {
      id: '/c/$slug/produtos'
      path: '/produtos'
      fullPath: '/c/$slug/produtos'
      preLoaderRoute: typeof CSlugProdutosRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/indique': {
      id: '/c/$slug/indique'
      path: '/indique'
      fullPath: '/c/$slug/indique'
      preLoaderRoute: typeof CSlugIndiqueRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/enquetes': {
      id: '/c/$slug/enquetes'
      path: '/enquetes'
      fullPath: '/c/$slug/enquetes'
      preLoaderRoute: typeof CSlugEnquetesRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/cupons': {
      id: '/c/$slug/cupons'
      path: '/cupons'
      fullPath: '/c/$slug/cupons'
      preLoaderRoute: typeof CSlugCuponsRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/creditos': {
      id: '/c/$slug/creditos'
      path: '/creditos'
      fullPath: '/c/$slug/creditos'
      preLoaderRoute: typeof CSlugCreditosRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/clube': {
      id: '/c/$slug/clube'
      path: '/clube'
      fullPath: '/c/$slug/clube'
      preLoaderRoute: typeof CSlugClubeRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/beneficios': {
      id: '/c/$slug/beneficios'
      path: '/beneficios'
      fullPath: '/c/$slug/beneficios'
      preLoaderRoute: typeof CSlugBeneficiosRouteImport
      parentRoute: typeof CSlugRoute
    }
    '/c/$slug/produtos/$productId': {
      id: '/c/$slug/produtos/$productId'
      path: '/$productId'
      fullPath: '/c/$slug/produtos/$productId'
      preLoaderRoute: typeof CSlugProdutosProductIdRouteImport
      parentRoute: typeof CSlugProdutosRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CSlugProdutosRouteChildren {
  CSlugProdutosProductIdRoute: typeof CSlugProdutosProductIdRoute
}

const CSlugProdutosRouteChildren: CSlugProdutosRouteChildren = {
  CSlugProdutosProductIdRoute: CSlugProdutosProductIdRoute,
}

const CSlugProdutosRouteWithChildren = CSlugProdutosRoute._addFileChildren(
  CSlugProdutosRouteChildren,
)

interface CSlugRouteChildren {
  CSlugBeneficiosRoute: typeof CSlugBeneficiosRoute
  CSlugClubeRoute: typeof CSlugClubeRoute
  CSlugCreditosRoute: typeof CSlugCreditosRoute
  CSlugCuponsRoute: typeof CSlugCuponsRoute
  CSlugEnquetesRoute: typeof CSlugEnquetesRoute
  CSlugIndiqueRoute: typeof CSlugIndiqueRoute
  CSlugProdutosRoute: typeof CSlugProdutosRouteWithChildren
  CSlugSobreRoute: typeof CSlugSobreRoute
  CSlugIndexRoute: typeof CSlugIndexRoute
}

const CSlugRouteChildren: CSlugRouteChildren = {
  CSlugBeneficiosRoute: CSlugBeneficiosRoute,
  CSlugClubeRoute: CSlugClubeRoute,
  CSlugCreditosRoute: CSlugCreditosRoute,
  CSlugCuponsRoute: CSlugCuponsRoute,
  CSlugEnquetesRoute: CSlugEnquetesRoute,
  CSlugIndiqueRoute: CSlugIndiqueRoute,
  CSlugProdutosRoute: CSlugProdutosRouteWithChildren,
  CSlugSobreRoute: CSlugSobreRoute,
  CSlugIndexRoute: CSlugIndexRoute,
}

const CSlugRouteWithChildren = CSlugRoute._addFileChildren(CSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BeneficiariosRoute: BeneficiariosRoute,
  CampanhasRoute: CampanhasRoute,
  CatalogoRoute: CatalogoRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FinanceiroRoute: FinanceiroRoute,
  LandingRoute: LandingRoute,
  NfcRoute: NfcRoute,
  PerfilRoute: PerfilRoute,
  CSlugRoute: CSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
